### ISSUE TITLE
编译报错缺少io.github.viscent.util.Tools这个类

### ISSUE THREAD

**Issue by lambdaoo** [Viscent/javamtp#5]
在io.github.viscent.mtpattern.ch7.pc.exmaple.AttachmentProcessor中使用了io.github.viscent.util.Tools
/workspace/JavaConcurrencyPatternInAction/src/main/java/io/github/viscent/mtpattern/ch7/pc/exmaple/AttachmentProcessor.java:28: 错误: 找不到符号
import io.github.viscent.util.Tools;
                             ^
  符号:   类 Tools
  位置: 程序包 io.github.viscent.util
/workspace/JavaConcurrencyPatternInAction/src/main/java/io/github/viscent/mtpattern/ch5/tpt/example/SomeService.java:20: 错误: 找不到符号
import io.github.viscent.util.Tools;
                             ^
  符号:   类 Tools
  位置: 程序包 io.github.viscent.util
/workspace/JavaConcurrencyPatternInAction/src/main/java/io/github/viscent/mtpattern/ch7/pc/exmaple/AttachmentProcessor.java:33: 错误: 找不到符号
            Tools
            ^
  符号:   变量 Tools
  位置: 类 AttachmentProcessor
/workspace/JavaConcurrencyPatternInAction/src/main/java/io/github/viscent/mtpattern/ch7/pc/exmaple/AttachmentProcessor.java:65: 错误: 找不到符号
                    Tools.randomPause(100, 80);
                    ^
  符号: 变量 Tools
/workspace/JavaConcurrencyPatternInAction/src/main/java/io/github/viscent/mtpattern/ch5/tpt/example/SomeService.java:50: 错误: 找不到符号
                Tools.randomPause(100, 50);
                ^
  符号:   变量 Tools
  位置: 类 SomeService.Consumer
5 个错误

**Comment by Viscent** [comment]
请先下载本书第1版的发布源码：https://github.com/Viscent/javamtp/tree/1stedition。
目前最新版的代码还在修改中，部分源码还没有更新上去。
